[project]
name = "inline_test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
run-tests = "inline_tests.runner:main"
